import { Menu, Sun, UserRound } from 'lucide-react'
import { useState } from 'react'
import { NavLink, Outlet } from 'react-router-dom'

const navigation = [{ label: 'Overview', items: [['Dashboard', '/dashboard']] }, { label: 'Intelligence', items: [['Village Intelligence', '/village-intelligence'], ['Solar Potential', '/solar-potential'], ['Financial Analysis', '/financial-analysis']] }, { label: 'Investment', items: [['Priority Ranking', '/priority-ranking'], ['Investment Optimizer', '/investment-optimizer']] }, { label: 'Monitoring', items: [['Lifecycle Monitoring', '/lifecycle-monitoring']] }]

export function AppShell() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  return <div className="min-h-screen bg-[#f7f5f0]"><header className="sticky top-0 z-[1000] flex h-16 items-center border-b border-[#e5e4de] bg-[#fffefa]/95 px-4 backdrop-blur sm:px-6"><button onClick={() => setMenuOpen(!menuOpen)} className="rounded p-2 text-slate-700 hover:bg-slate-100" aria-label="Open navigation"><Menu size={21} /></button><div className="ml-3 flex items-center gap-2 font-semibold tracking-tight text-[#172033]"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#f2b84b] text-[#172033]"><Sun size={17} /></span>SolarShakti</div><div className="ml-auto hidden text-sm text-slate-500 sm:block">Rural Solar Intelligence</div><div className="ml-4"><button onClick={() => setProfileOpen(!profileOpen)} className="flex h-9 w-9 items-center justify-center rounded-full border border-[#dfe3e2] bg-white text-slate-700" aria-label="Open profile menu"><UserRound size={18} /></button></div>{profileOpen && <div className="absolute right-4 top-full z-10 mt-2 w-56 max-w-[calc(100vw-2rem)] border border-[#e2e3df] bg-white p-3 text-sm shadow-lg sm:right-6"><p className="font-medium text-[#172033]">Government user</p><p className="mt-1 text-xs text-slate-500">Profile integration pending</p><hr className="my-3 border-[#e8e8e4]" /><button className="block py-1 text-slate-600">Settings</button><button className="block py-1 text-slate-600">Log out</button></div>}</header>{menuOpen && <><button className="fixed inset-x-0 bottom-0 top-16 z-[800] bg-slate-950/20" onClick={() => setMenuOpen(false)} aria-label="Close navigation" /><aside className="fixed bottom-0 left-0 top-16 z-[900] w-[calc(100vw-1rem)] max-w-72 overflow-y-auto border-r border-[#e5e4de] bg-[#fffefa] p-5 shadow-xl">{navigation.map((group) => <section key={group.label} className="mb-6"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400">{group.label}</p>{group.items.map(([label, to]) => <NavLink key={to} to={to} onClick={() => setMenuOpen(false)} className={({ isActive }) => `mb-1 block rounded px-3 py-2 text-sm ${isActive ? 'bg-[#f7efd9] font-medium text-[#8a620f]' : 'text-slate-600 hover:bg-slate-100'}`}>{label}</NavLink>)}</section>)}</aside></>}<main><Outlet /></main></div>
}
