import { useQuery } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { solarShaktiApi } from '../../services/api'
import type { VillageRanking } from '../../types/api'
import { InfoTooltip } from '../ui/InfoTooltip'

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
export function AnalyticalOverview({ ranking, selectedId, stateName }: { ranking: VillageRanking[]; selectedId?: string; stateName: string }) { const solar = useQuery({ queryKey: ['village-solar', selectedId], queryFn: () => solarShaktiApi.getVillageSolar(selectedId!), enabled: Boolean(selectedId) }); const ranked = [...ranking].sort((a, b) => a.rank - b.rank); return <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="mb-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#a4771b]">Evidence at a glance</p><h2 className="mt-1 text-2xl font-semibold text-[#172033]">Analytical Overview</h2></div><div className="grid gap-5 lg:grid-cols-2"><ChartCard title="Village Generation Trend" tooltip="Shows the selected village's monthly solar data from the backend. Use this view to understand how solar resource availability changes across the year." subtitle={selectedId ? 'Selected village monthly solar irradiance' : 'Select a village to display monthly solar data'}>{!selectedId ? <EmptyChart text="No village selected" /> : solar.isLoading ? <EmptyChart text="Loading monthly solar data…" /> : solar.isError ? <EmptyChart text="Monthly solar data is unavailable." /> : <ResponsiveContainer width="100%" height={250}><LineChart data={solar.data?.data.map((point) => ({ month: months[point.month - 1], irradiance: point.solar_irradiance }))}><CartesianGrid vertical={false} stroke="#e8e8e4" /><XAxis dataKey="month" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} width={34} /><Tooltip /><Line type="monotone" dataKey="irradiance" name="Solar irradiance" stroke="#b77b12" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer>}</ChartCard><ChartCard title="State Priority Ranking" tooltip="Compares villages using their backend-provided investment scores. Villages are ordered by priority rank to help identify higher-priority investment opportunities." subtitle={`${stateName} village investment scores by priority rank`}>{<ResponsiveContainer width="100%" height={250}><BarChart data={ranked}><CartesianGrid vertical={false} stroke="#e8e8e4" /><XAxis dataKey="village_name" tickLine={false} axisLine={false} tick={{ fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} width={34} /><Tooltip /><Bar dataKey="investment_score" name="Investment score" fill="#2d7a78" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer>}</ChartCard></div></section> }
function ChartCard({ title, tooltip, subtitle, children }: { title: string; tooltip: string; subtitle: string; children: React.ReactNode }) { return <article className="overflow-visible border border-[#e4e4df] bg-[#fffefa] p-5 shadow-[0_1px_3px_rgba(23,32,51,.04)]"><h3 className="flex items-center gap-1.5 font-semibold text-[#172033]">{title}<InfoTooltip label={`About ${title}`}>{tooltip}</InfoTooltip></h3><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-5">{children}</div></article> }
function EmptyChart({ text }: { text: string }) { return <div className="flex h-[250px] items-center justify-center border border-dashed border-[#deded8] text-sm text-slate-500">{text}</div> }
