import { divIcon } from 'leaflet'
import { MapContainer, Marker, TileLayer } from 'react-leaflet'
import type { VillageGeoJson, VillageRanking } from '../../types/api'

interface Props { mapData: VillageGeoJson; ranking: VillageRanking[]; selectedId?: string; onSelect: (id: string) => void }
const priorityColors = ['#e53935', '#f4511e', '#fb8c00', '#f5b829', '#f6dc5c']
function priorityColor(rank: number, highestRank: number) { return priorityColors[Math.min(Math.floor(((rank - 1) / Math.max(highestRank - 1, 1)) * priorityColors.length), priorityColors.length - 1)] }
function markerIcon(rank: number, highestRank: number, selected: boolean, showRankLabel: boolean) { return divIcon({ className: 'village-marker', html: `<div style="width:${selected ? 32 : 27}px;height:${selected ? 32 : 27}px;border:2px solid white;border-radius:50%;background:${priorityColor(rank, highestRank)};box-shadow:0 2px 7px rgba(23,32,51,.3);display:flex;align-items:center;justify-content:center;color:#172033;font:700 10px Inter,sans-serif">${showRankLabel ? rank : ''}</div>`, iconSize: [selected ? 32 : 27, selected ? 32 : 27], iconAnchor: [selected ? 16 : 13.5, selected ? 16 : 13.5] }) }
export function VillageMap({ mapData, ranking, selectedId, onSelect }: Props) { const byId = new Map(ranking.map((village) => [village.village_id, village])); const highestRank = Math.max(...mapData.features.map((feature) => byId.get(feature.properties.id)?.rank ?? feature.properties.rank)); const showRankLabels = mapData.features.length <= 100; return <MapContainer center={[20.13, 73.92]} zoom={10} scrollWheelZoom className="relative z-0 h-full min-h-[420px] w-full"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://tile.openstreetmap.org/{z}/{x}/{y}.png" />{mapData.features.map((feature) => { const village = byId.get(feature.properties.id); const rank = village?.rank ?? feature.properties.rank; return <Marker key={feature.properties.id} position={[feature.geometry.coordinates[1], feature.geometry.coordinates[0]]} icon={markerIcon(rank, highestRank, selectedId === feature.properties.id, showRankLabels)} eventHandlers={{ click: () => onSelect(feature.properties.id) }} /> })}</MapContainer> }
